config/routes.rb
Rails.application.routes.draw do
  root to: "front#index"

  # About
  get '/about', to: "front#about"
  get '/price', to: "front#price"

  # Search
  get '/search', to: "front#search"

  # Contact
  get '/contact', to: "front#contact"
  post '/contact/send' => "front#contactSubmit"

  # Upload
  post "/upload_image" => "upload#upload_image"
  post '/delete_image' => 'upload#delete_image'
  get '/load_images'   => 'upload#load_images', :defaults => { :format => 'json' }
  
  # Back-End
  namespace :acp do
    get '/', to: "main#index"

    resources :posts

    resources :categories do
      resources :subcategories
    end

    resources :pricings

    get '/setting', to: "setting#index"
    get '/setting/cache', to: "setting#cache"
    post '/setting/cache/clean', to: "setting#clean"
    match '/setting/update', to: "setting#update", via: [:post, :patch]
  end

  # Authenticator Admin
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords"
  }

  # Post
  get '/:category', to: "posts#index"
  get '/:category/:subcategory', to: "posts#category"
  get '/:category/:subcategory/:post', to: "posts#detail"

  match '*path' => 'front#errors', via: :all
end

app/controllers/acp/categories_controller.rb
class Acp::CategoriesController < AcpController
	before_action :find_category, only: [:show, :edit, :update, :destroy]

	def index
		@categories = Category.where(category_type: params[:type].present? ? params[:type] : [1,2,3]).order('category_type ASC','id ASC')
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			Category.last.update(thumb_url: Category.last.thumb.url(:thumb))
			redirect_to acp_categories_path
		end
	end

	def edit
	end

	def update
		if @category.update(category_params)
			@category.update(thumb_url: @category.thumb.url(:thumb))
      redirect_to acp_categories_path
    else
      render 'edit'
    end
	end

	def destroy
		if @category.destroy
      redirect_to acp_categories_path
    end
	end

	private
    def category_params
    	params.require(:category).permit(:title, :slug, :description, :detail, :category_type, :thumb, :featured, :hidden)
    end

    def find_category
    	@category = Category.find(params[:id])
    end
end

app/controllers/acp/main_controller.rb
class Acp::MainController < AcpController
	def index
	end
end

app/controllers/acp/posts_controller.rb
class Acp::PostsController < AcpController
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			Post.last.update(thumb_url: Post.last.thumb.url(:full))
			redirect_to acp_posts_path
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			@post.update(thumb_url: @post.thumb.url(:full))
      redirect_to acp_posts_path
    else
      render 'edit'
    end
	end

	def destroy
		if @post.destroy
      redirect_to acp_posts_path
    end
	end

	private
    def post_params
    	params.require(:post).permit(:title, :slug, :description, :category, :content, :thumb, :featured, :hidden)
    end

    def find_post
    	@post = Post.find(params[:id])
    end
end

app/controllers/acp/pricings_controller.rb
class Acp::PricingsController < AcpController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@pricings = Pricing.all.order("created_at ASC")
	end

	def new
		@pricing = Pricing.new
	end

	def create
		@pricing = Pricing.new(pricing_params)

		if @pricing.save
			@pricing.update(thumb_url: @pricing.thumb.url)
			redirect_to acp_pricings_path
		end
	end

	def edit
	end

	def update
		if @pricing.update(pricing_params)
			@pricing.update(thumb_url: @pricing.thumb.url)
      redirect_to acp_pricings_path
    else
      render 'edit'
    end
	end

	def destroy
		if @pricing.destroy
      redirect_to acp_pricings_path
    end
	end

	private
    def pricing_params
    	params.require(:pricing).permit(:title, :slug, :description, :pricing, :thumb, :hidden)
    end

    def find_post
    	@pricing = Pricing.find(params[:id])
    end
end

app/controllers/acp/setting_controller.rb
class Acp::SettingController < AcpController
	def index
		@setting = Setting.first.nil? ? Setting.new : Setting.first
	end

	def update
		@setting = Setting.first.nil? ? Setting.new(setting_params) : Setting.first.update(setting_params)

		if Setting.first.nil?
			@setting.save
		end

		redirect_to acp_setting_path
	end

	def clean
		$redis.del "categories"
		$redis.del "subcategories"
		$redis.del "posts"
		$redis.del "settings"

		redirect_back(fallback_location: acp_path)
	end

	private
		def setting_params
			params.require(:setting).permit(:title, :description, :about, :phone, :email, :address, :company, :g_verification, :g_analytic, :fb_app, :fb_pixel)
		end
end

app/controllers/acp/subcategories_controller.rb
class Acp::SubcategoriesController < AcpController
	before_action :find_subcategory, only: [:show, :edit, :update, :destroy]

	def index
		@category = Category.find(params[:category_id])
		redirect_to acp_category_path(@category)
	end

	def new
		@category = Category.find(params[:category_id])
		@subcategory = @category.subcategories.new
	end

	def create
		@category = Category.find(params[:category_id])
		@subcategory = @category.subcategories.new(subcategory_params)

		if @subcategory.save
			Subcategory.last.update(thumb_url: Subcategory.last.thumb.url(:full))
			redirect_to acp_category_path(@category)
		end
	end

	def edit
	end

	def update
		if @subcategory.update(subcategory_params)
			@subcategory.update(thumb_url: @subcategory.thumb.url(:full))
      redirect_to acp_category_path(@category)
    else
      render 'edit'
    end
	end

	def destroy
		if @subcategory.destroy
      redirect_to acp_category_path(@category)
    end
	end

	private
    def subcategory_params
    	params.require(:subcategory).permit(:title, :slug, :description, :detail, :thumb, :featured, :hidden)
    end

    def find_subcategory
    	@category = Category.find(params[:category_id])
    	@subcategory = @category.subcategories.find(params[:id])
    end
end

app/controllers/acp_controller.rb
class AcpController < ApplicationController
	before_action :authenticate_admin!
end

app/views/acp/shared/_sidebar.html.erb
<div class="admin__control-navigator-global">
	<div class="admin__control-navigator-global__menu-list">
		<div class="menu__list">
			<a href="<%= acp_path %>" class="menu__list-item<% if current_page?(acp_path) %> active<% end %>">
				<span class="home_ic">
					<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path d="M372.6,1053.778V1046h6.222v7.778Zm0,6.222v-4.667h6.222V1060Zm7.778-14H386.6v4.667h-6.222Zm0,14v-7.778H386.6V1060Z" transform="translate(-372.6 -1046)" fill="#fff"/></svg>
				</span>
			</a>
			<a nohref class="menu__list-item navigationAdd">
				<span class="add_ic">
					<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path d="M19,151.2H13v6H11v-6H5v-2h6v-6h2v6h6Z" transform="translate(-5 -143.2)" fill="#fff"/></svg>
				</span>
			</a>
			<a href="<%= acp_setting_path %>" class="menu__list-item<% if current_page?(acp_setting_path) %> active<% end %>">
				<span class="settings_ic">
					<svg xmlns="http://www.w3.org/2000/svg" width="19.618" height="20" viewBox="0 0 19.618 20"><path d="M56.4,1160.4l2.1,1.6a.592.592,0,0,1,.1.7l-2,3.5a.445.445,0,0,1-.6.2l-2.5-1a8.152,8.152,0,0,1-1.7,1l-.4,2.6c-.1.3-.2.4-.5.4h-4a.51.51,0,0,1-.5-.4l-.4-2.6a5.852,5.852,0,0,1-1.7-1l-2.5,1a.445.445,0,0,1-.6-.2l-2-3.5a.483.483,0,0,1,.1-.7l2.1-1.6v-2l-2.1-1.6a.592.592,0,0,1-.1-.7l2-3.5a.445.445,0,0,1,.6-.2l2.5,1a8.152,8.152,0,0,1,1.7-1l.4-2.6c.1-.3.2-.4.5-.4h4a.51.51,0,0,1,.5.4l.4,2.6a5.852,5.852,0,0,1,1.7,1l2.5-1a.445.445,0,0,1,.6.2l2,3.5a.483.483,0,0,1-.1.7l-2.1,1.6v2Zm-9.9,1.5a3.625,3.625,0,1,0-1-2.5A3.317,3.317,0,0,0,46.5,1161.9Z" transform="translate(-39.091 -1149.4)" fill="#fff"/></svg>
				</span>
			</a>
		</div>
	</div>
</div>
<div class="admin__control-navigator-wrapper">
	<div class="admin__control-navigator-wrapper-header">
		<p>Content Management System</p>
	</div>
	<div class="admin__control-navigator-wrapper__action-list">
		<div class="action__list">
			<% if controller_name != "setting" %>
				<a href="<%= acp_path %>" class="action__list-item<% if request.path == acp_path %> active<% end %>">
					Trang Chính
				</a>
				<a href="<%= acp_posts_path %>" class="action__list-item<% if request.path == acp_posts_path || current_page?(new_acp_post_path) || controller_name == "posts" && request.path == edit_acp_post_path %> active<% end %>">
					Bài Viết
				</a>
				<a href="<%= acp_categories_path %>" class="action__list-item<% if request.path == acp_categories_path || current_page?(new_acp_category_path) || controller_name == "categories" && request.path == edit_acp_category_path %> active<% end %>">
					Quản Lý Danh Mục
				</a>
				<a href="<%= acp_pricings_path %>" class="action__list-item<% if request.path == acp_pricings_path || current_page?(new_acp_pricing_path) || controller_name == "pricings" && request.path == edit_acp_pricing_path %> active<% end %>">
					Bảng Giá
				</a>
			<% else %>
				<a href="<%= acp_setting_path %>" class="action__list-item<% if current_page?(acp_setting_path) %> active<% end %>">
					Thiết Lập Chung
				</a>
				<a href="<%= acp_setting_cache_path %>" class="action__list-item<% if current_page?(acp_setting_cache_path) %> active<% end %>">
					Cache
				</a>
			<% end %>
		</div>
	</div>
</div>