config/routes.rb
Rails.application.routes.draw do
  root to: "front#index"

  # About
  get '/about', to: "front#about"
  get '/price', to: "front#price"

  # Search
  get '/search', to: "front#search"

  # Contact
  get '/contact', to: "front#contact"
  post '/contact/send' => "front#contactSubmit"

  # Upload
  post "/upload_image" => "upload#upload_image"
  post '/delete_image' => 'upload#delete_image'
  get '/load_images'   => 'upload#load_images', :defaults => { :format => 'json' }
  
  # Back-End
  namespace :acp do
    get '/', to: "main#index"

    resources :posts

    resources :categories do
      resources :subcategories
    end

    resources :pricings

    get '/setting', to: "setting#index"
    get '/setting/cache', to: "setting#cache"
    post '/setting/cache/clean', to: "setting#clean"
    match '/setting/update', to: "setting#update", via: [:post, :patch]
  end

  # Authenticator Admin
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords"
  }

  # Post
  get '/:category', to: "posts#index"
  get '/:category/:subcategory', to: "posts#category"
  get '/:category/:subcategory/:post', to: "posts#detail"

  match '*path' => 'front#errors', via: :all
end

app/models/pricing.rb
class Pricing < ApplicationRecord
	after_save :clear_cache
	after_destroy :clear_cache

	has_attached_file :thumb,
	{
		default_url: ":attachment/null",
		s3_permissions: :private,
	  path: "/uploads/:attachment/:style/:filename",
	  validate_media_type: false
	}
	validates_attachment_file_name :thumb, :matches => [/png\Z/, /jpe?g\Z/, /svg\Z/]

	private
	  def clear_cache
	    $redis.del "pricings"
	  end
end

app/controllers/acp/categories_controller.rb
class Acp::CategoriesController < AcpController
	before_action :find_category, only: [:show, :edit, :update, :destroy]

	def index
		@categories = Category.where(category_type: params[:type].present? ? params[:type] : [1,2,3]).order('category_type ASC','id ASC')
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			Category.last.update(thumb_url: Category.last.thumb.url(:thumb))
			redirect_to acp_categories_path
		end
	end

	def edit
	end

	def update
		if @category.update(category_params)
			@category.update(thumb_url: @category.thumb.url(:thumb))
      redirect_to acp_categories_path
    else
      render 'edit'
    end
	end

	def destroy
		if @category.destroy
      redirect_to acp_categories_path
    end
	end

	private
    def category_params
    	params.require(:category).permit(:title, :slug, :description, :detail, :category_type, :thumb, :featured, :hidden)
    end

    def find_category
    	@category = Category.find(params[:id])
    end
end

app/controllers/acp/main_controller.rb
class Acp::MainController < AcpController
	def index
	end
end

app/controllers/acp/posts_controller.rb
class Acp::PostsController < AcpController
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			Post.last.update(thumb_url: Post.last.thumb.url(:full))
			redirect_to acp_posts_path
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			@post.update(thumb_url: @post.thumb.url(:full))
      redirect_to acp_posts_path
    else
      render 'edit'
    end
	end

	def destroy
		if @post.destroy
      redirect_to acp_posts_path
    end
	end

	private
    def post_params
    	params.require(:post).permit(:title, :slug, :description, :category, :content, :thumb, :featured, :hidden)
    end

    def find_post
    	@post = Post.find(params[:id])
    end
end

app/controllers/acp/pricings_controller.rb
class Acp::PricingsController < AcpController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@pricings = Pricing.all.order("created_at ASC")
	end

	def new
		@pricing = Pricing.new
	end

	def create
		@pricing = Pricing.new(pricing_params)

		if @pricing.save
			@pricing.update(thumb_url: @pricing.thumb.url)
			redirect_to acp_pricings_path
		end
	end

	def edit
	end

	def update
		if @pricing.update(pricing_params)
			@pricing.update(thumb_url: @pricing.thumb.url)
      redirect_to acp_pricings_path
    else
      render 'edit'
    end
	end

	def destroy
		if @pricing.destroy
      redirect_to acp_pricings_path
    end
	end

	private
    def pricing_params
    	params.require(:pricing).permit(:title, :slug, :description, :pricing, :thumb, :hidden)
    end

    def find_post
    	@pricing = Pricing.find(params[:id])
    end
end

app/controllers/acp/setting_controller.rb
class Acp::SettingController < AcpController
	def index
		@setting = Setting.first.nil? ? Setting.new : Setting.first
	end

	def update
		@setting = Setting.first.nil? ? Setting.new(setting_params) : Setting.first.update(setting_params)

		if Setting.first.nil?
			@setting.save
		end

		redirect_to acp_setting_path
	end

	def clean
		$redis.del "categories"
		$redis.del "subcategories"
		$redis.del "posts"
		$redis.del "settings"

		redirect_back(fallback_location: acp_path)
	end

	private
		def setting_params
			params.require(:setting).permit(:title, :description, :about, :phone, :email, :address, :company, :g_verification, :g_analytic, :fb_app, :fb_pixel)
		end
end

app/controllers/acp/subcategories_controller.rb
class Acp::SubcategoriesController < AcpController
	before_action :find_subcategory, only: [:show, :edit, :update, :destroy]

	def index
		@category = Category.find(params[:category_id])
		redirect_to acp_category_path(@category)
	end

	def new
		@category = Category.find(params[:category_id])
		@subcategory = @category.subcategories.new
	end

	def create
		@category = Category.find(params[:category_id])
		@subcategory = @category.subcategories.new(subcategory_params)

		if @subcategory.save
			Subcategory.last.update(thumb_url: Subcategory.last.thumb.url(:full))
			redirect_to acp_category_path(@category)
		end
	end

	def edit
	end

	def update
		if @subcategory.update(subcategory_params)
			@subcategory.update(thumb_url: @subcategory.thumb.url(:full))
      redirect_to acp_category_path(@category)
    else
      render 'edit'
    end
	end

	def destroy
		if @subcategory.destroy
      redirect_to acp_category_path(@category)
    end
	end

	private
    def subcategory_params
    	params.require(:subcategory).permit(:title, :slug, :description, :detail, :thumb, :featured, :hidden)
    end

    def find_subcategory
    	@category = Category.find(params[:category_id])
    	@subcategory = @category.subcategories.find(params[:id])
    end
end

app/controllers/acp_controller.rb
class AcpController < ApplicationController
	before_action :authenticate_admin!
end

app/controllers/pricings_controller.rb
class PricingsController < ApplicationController
end

app/views/acp/pricings/_form.html.erb
<%= form_for [:acp, @pricing], html: { id: 'form', multipart: true } do |f|%>
  <div class="admin__control-container-wrapper bg-white remote">
    <h5 class="mt-2 float-left"><%= action_name == "new" ? "Thêm" : "Sửa" %> Giá Dịch Vụ</h5>
    <div class="form-group vertical row mt-4">
      <%= f.label :title, 'Title', class: 'col-sm-2 col-form-label text-right' %>
      <div class="col-sm-9 col-form-value">
        <%= f.text_field :title, class: 'form-control', :required => true %>
        <small class="text-muted">Tiêu đề giới hạn từ 10 - 100 ký tự.</small>
      </div>
    </div>

    <div class="form-group vertical row">
      <%= f.label :description, 'Giới Thiệu', class: 'col-sm-2 col-form-label text-right' %>
      <div class="col-sm-9 col-form-value">
        <%= f.text_area :description, size: '50x2', class: 'form-control', :required => true %>
        <small class="text-muted">Đoạn giới thiệu dịch vụ giới hạn từ 50 - 200 ký tự.</small>
      </div>
    </div>

    <div class="form-group vertical row mt-4">
      <%= f.label :pricing, 'Pricing', class: 'col-sm-2 col-form-label text-right' %>
      <div class="col-sm-9 col-form-value">
        <%= f.text_field :pricing, class: 'form-control', :required => true %>
        <small class="text-muted">Đặt giá cho dịch vụ</small>
      </div>
    </div>

    <div class="form-group vertical row mt-4">
      <%= f.label :slug, 'Slug', class: 'col-sm-2 col-form-label text-right' %>
      <div class="col-sm-9 col-form-value">
        <%= f.text_field :slug, class: 'form-control', :required => true %>
        <small class="text-muted">Đặt đường dẫn tới chi tiết dịch vụ</small>
      </div>
    </div>

    <div class="form-group vertical row">
      <%= f.label :thumb, 'Ảnh Thumbnail', class: 'col-sm-2 col-form-label text-right' %>
      <div class="col-sm-9 col-form-value">
        <% if action_name == "edit" && @pricing.thumb.exists? && params[:thumb].nil? %>
          <div class="admin__control-container-additional-thumb clearfix">
            <div class="admin__control-container-additional-thumb-review">
              <a href="<%= request.fullpath %>?thumb=replace" class="admin__control-container-additional-thumb-review-edit">
                <span class="close_ic">
                  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path d="M388.6,875.4,383,881l5.6,5.6-1.4,1.4-5.6-5.6L376,888l-1.4-1.4,5.6-5.6-5.6-5.6L376,874l5.6,5.6,5.6-5.6Z" transform="translate(-374.6 -874)" fill="#fff"/></svg>
                </span>
              </a>
              <img src="<%= @pricing.thumb.url %>">
            </div>
            <div class="admin__control-container-additional-thumb-info">
              <p>Filename: <%= @pricing.thumb_file_name %></p>
            </div>
          </div>
        <% else %>
        <div class="input-group customize">
          <div class="custom-file">
            <%= f.file_field :thumb, class: 'custom-file-input', id: "thumbUpload" %>
            <label class="custom-file-label" for="thumbUpload">Chọn ảnh tải lên</label>
          </div>
        </div>
        <% if action_name == "edit" && @pricing.thumb.exists? && params[:thumb] == "replace" %>
          <small><a href="<%= edit_acp_pricing_path(@pricing) %>">Huỷ</a></small>
        <% end %>
        <% end %>
      </div>
    </div>
    
    <div class="form-group row mb-0">
      <%= f.label :hidden, 'Ẩn', class: 'col-sm-2 col-form-label text-right' %>
      <div class="col-sm-9 col-form-value">
        <div class="switch-group clearfix">
          <label class="switch">
            <%= f.check_box :hidden, { class: 'custom-control-input', checked: @pricing.hidden }, "true", "false" %>
            <span class="slider round"></span>
          </label>
          <%= f.label :hidden, 'Ẩn dịch vụ này', class: 'switch-group-label' %>
        </div>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-sm-12">
        <%= button_tag(type: "submit", class: "btn btn-default primary-nd rounded mr-2") do %>
          Lưu Giá Dịch Vụ
        <% end %>
        <a href="<%= url_for(:back) %>" class="btn btn-default dark outline rounded">Quay Lại</a>
      </div>
    </div>
  </div>
<% end %>

app/views/acp/pricings/edit.html.erb
<div class="container-fluid admin__control">
  <div class="row">
    <div class="admin__control-navigator clearfix">
      <%= render 'acp/shared/sidebar' %>
    </div>
    <div class="admin__control-container clearfix">
      <div class="admin__control-container-resize"></div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/acp/pricings/index.html.erb
<div class="container-fluid admin__control">
  <div class="row">
    <div class="admin__control-navigator clearfix">
      <%= render 'acp/shared/sidebar' %>
    </div>
    <div class="admin__control-container clearfix">
      <div class="admin__control-container-resize"></div>
      <div class="admin__control-container-wrapper bg-white full">
        <div class="admin__control-container-wrapper-heading clearfix">
          <h5 class="mt-2 float-left">Tất Cả Giá Dịch Vụ</h5>
          <a href="<%= new_acp_pricing_path %>" class="btn btn-default primary rounded outline btn-md float-right"><span class="add_ic"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path d="M19,151.2H13v6H11v-6H5v-2h6v-6h2v6h6Z" transform="translate(-5 -143.2)" fill="var(--main-color)"/></svg></span>&nbsp;&nbsp;Thêm Mới</a>
        </div>

        <div class="form-group mt-3">
          <div class="form-search">
            <span class="search_ic"></span>
            <input type="" name="" id="search" class="form-control" placeholder="Tìm kiếm...">
          </div>
        </div>
        <% if @pricings.present? %>
        <table class="table croped mt-3 mb-0">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Tên Dịch Vụ</th>
              <th scope="col">Giá</th>
              <th scope="col">Ẩn</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @pricings.each do |pricing| %>
              <tr>
                <td><%= pricing["id"] %></td>
                <td><%= pricing["title"] %></td>
                <td><%= pricing["pricing"] %></td>
                <td><span class="status status-<%= pricing["hidden"] %>"><%= boolean(pricing["hidden"]).titlecase %></span></td>
                <td>
                  <div class="ribbon">
                    <span class="admin-edit_ic ribbon-show"></span>
                    <div class="ribbon-action rounded">
                      <div class="ribbon-action-list">
                        <a class="ribbon-action-list-item" href="<%= edit_acp_pricing_path(pricing["id"]) %>">Sửa</a>
                        <a class="ribbon-action-list-item primary" rel="nofollow" data-confirm="Are you sure?" data-method="delete" href="<%= acp_pricing_path(pricing["id"]) %>">Xoá</a>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
          <span class="small">No record found!</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/acp/pricings/new.html.erb
<div class="container-fluid admin__control">
  <div class="row">
    <div class="admin__control-navigator clearfix">
      <%= render 'acp/shared/sidebar' %>
    </div>
    <div class="admin__control-container clearfix">
      <div class="admin__control-container-resize"></div>
      <%= render 'form' %>
    </div>
  </div>
</div>